modLoader="javafml" #mandatory
loaderVersion="[38,)" #mandatory
issueTrackerURL="${issues_url}"
sourcesUrl="${sources_url}"
license="${license}"

[[mods]] #mandatory
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_display_name}"
    displayURL="${homepage_url}"
    authors="${mod_author}"
    credits="${mod_credits}"
    description='''${mod_description}'''
    logoFile="${logo_forge}"
    logoBlur=false

[dependencies]
"${mod_id}" = [
    { modId = "forge", mandatory = true, versionRange = "[46.0.1,)", ordering = "NONE", side = "BOTH" },
    { modId = "minecraft", mandatory = true, versionRange = "[1.20.1,1.21)", ordering = "NONE", side = "BOTH" },
]
