org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Common
parchment_minecraft_version=1.21.10
parchment_mappings_version=2025.10.12
minecraft_version=1.21.11
neoform_version=1.21.11-20251209.172050

# NeoForge
neoforge_version=21.11.0-beta

# Fabric
fabric_loader_version=0.18.2
fabric_api_version=0.139.4+1.21.11

# MC dependencies
jetbrains_annotations_version=26.0.1
mixin_version=0.15.4+mixin.0.8.7
mixin_extras_version=0.4.1
asm_version=9.7

## Mod Properties
mod_id=repurposed_structures
mod_name=Repurposed Structures
mod_version=7.6.1
mod_description=Adds more variations of vanilla structures and features!
mod_author=TelepathicGrunt
mod_credits=Special thanks to /r/l-ll-ll-l_IsDisLoss, miguelforge, and cannon_foddr for donating some structures to this mod!
license=GNU Lesser General Public License v3.0
license_url=https://github.com/TelepathicGrunt/RepurposedStructures/blob/HEAD/LICENSE.txt
sources_url=https://github.com/TelepathicGrunt/RepurposedStructures
issues_url=https://github.com/TelepathicGrunt/RepurposedStructures/issues
homepage_url=https://www.curseforge.com/minecraft/mc-mods/repurposed-structures
logo_neoforge=assets/repurposed_structures/repurposed_structures_logo_wide.png
logo_fabric=assets/repurposed_structures/repurposed_structures_logo.png

# Publishing
mod_group_id=com.telepathicgrunt
curseforge_id_neoforge=368293
curseforge_id_fabric=391366
modrinth_id_neoforge=QDNS5oAT
modrinth_id_fabric=muf0XoRe

# Libraries
midnightlib=1.9.1+1.21.10-fabric
mod_menu=17.0.0-alpha.1

# Helper Dependencies that only exist at runtime
commandstructures_neoforge=4.4.4+1.21.6
commandstructures_fabric=4.4.4+1.21.6
structurevoidtoggle_neoforge=4.5.3+1.21.9
structurevoidtoggle_fabric=4.5.3+1.21.9
