org.gradle.jvmargs=-Xmx4G
minecraft_version=1.21.4
mod_id=repurposed_structures
mod_version=7.5.13
maven_group=com.telepathicgrunt

fabric_loader_version=0.16.9
fabric_api_version=0.111.0+1.21.4

neoforge_version=21.4.12-beta

# Libraries
midnightlib=1.5.7-fabric
mixin_extras=0.3.6

# Libraries
mod_menu=13.0.0-beta.1

# Helper Dependencies that only exist at runtime
commandstructures_neoforge=4.4.3+1.21.4
commandstructures_fabric=4.4.3+1.21.4
structurevoidtoggle_neoforge=4.4.1+1.21.4
structurevoidtoggle_fabric=4.4.1+1.21.4
