package com.telepathicgrunt.repurposedstructures.modinit;

import com.google.common.collect.ImmutableList;
import com.telepathicgrunt.repurposedstructures.RepurposedStructures;
import com.telepathicgrunt.repurposedstructures.mixin.PillagerOutpostFeatureAccessor;
import com.telepathicgrunt.repurposedstructures.world.structures.*;
import com.telepathicgrunt.repurposedstructures.world.structures.pieces.RSMineshaftPieces;
import net.fabricmc.fabric.api.structure.v1.FabricStructureBuilder;
import net.minecraft.util.Identifier;
import net.minecraft.world.gen.GenerationStep;
import net.minecraft.world.gen.chunk.StructureConfig;
import net.minecraft.world.gen.chunk.StructuresConfig;
import net.minecraft.world.gen.feature.DefaultFeatureConfig;
import net.minecraft.world.gen.feature.FeatureConfig;
import net.minecraft.world.gen.feature.StructureFeature;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;


public class RSStructures {
    public static final Map<StructureFeature<?>, StructureConfig> RS_STRUCTURES = new HashMap<>();
    public static final Set<Identifier> RS_STRUCTURE_START_PIECES = new HashSet<>();

    public static StructureFeature<DefaultFeatureConfig> BIRCH_MINESHAFT = new RSMineshaftStructure(RSMineshaftPieces.Type.BIRCH, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.spawnrate.birchMineshaftSpawnrate, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.maxHeight.birchMineshaftMaxHeight, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.minHeight.birchMineshaftMinHeight);
    public static StructureFeature<DefaultFeatureConfig> DESERT_MINESHAFT = new RSMineshaftStructure(RSMineshaftPieces.Type.DESERT, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.spawnrate.desertMineshaftSpawnrate, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.maxHeight.desertMineshaftMaxHeight, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.minHeight.desertMineshaftMinHeight);
    public static StructureFeature<DefaultFeatureConfig> END_MINESHAFT = new RSMineshaftEndStructure(RSMineshaftPieces.Type.END, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.spawnrate.endMineshaftSpawnrate, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.maxHeight.endMineshaftMaxHeight, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.minHeight.endMineshaftMinHeight);
    public static StructureFeature<DefaultFeatureConfig> NETHER_MINESHAFT = new RSMineshaftStructure(RSMineshaftPieces.Type.NETHER, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.spawnrate.netherMineshaftSpawnrate, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.maxHeight.netherMineshaftMaxHeight, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.minHeight.netherMineshaftMinHeight);
    public static StructureFeature<DefaultFeatureConfig> ICY_MINESHAFT = new RSMineshaftStructure(RSMineshaftPieces.Type.ICY, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.spawnrate.icyMineshaftSpawnrate, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.maxHeight.icyMineshaftMaxHeight, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.minHeight.icyMineshaftMinHeight);
    public static StructureFeature<DefaultFeatureConfig> JUNGLE_MINESHAFT = new RSMineshaftStructure(RSMineshaftPieces.Type.JUNGLE, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.spawnrate.jungleMineshaftSpawnrate, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.maxHeight.jungleMineshaftMaxHeight, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.minHeight.jungleMineshaftMinHeight);
    public static StructureFeature<DefaultFeatureConfig> OCEAN_MINESHAFT = new RSMineshaftStructure(RSMineshaftPieces.Type.OCEAN, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.spawnrate.oceanMineshaftSpawnrate, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.maxHeight.oceanMineshaftMaxHeight, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.minHeight.oceanMineshaftMinHeight);
    public static StructureFeature<DefaultFeatureConfig> SAVANNA_MINESHAFT = new RSMineshaftStructure(RSMineshaftPieces.Type.SAVANNA, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.spawnrate.savannaMineshaftSpawnrate, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.maxHeight.savannaMineshaftMaxHeight, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.minHeight.savannaMineshaftMinHeight);
    public static StructureFeature<DefaultFeatureConfig> STONE_MINESHAFT = new RSMineshaftStructure(RSMineshaftPieces.Type.STONE, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.spawnrate.stoneMineshaftSpawnrate, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.maxHeight.stoneMineshaftMaxHeight, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.minHeight.stoneMineshaftMinHeight);
    public static StructureFeature<DefaultFeatureConfig> SWAMP_OR_DARK_FOREST_MINESHAFT = new RSMineshaftStructure(RSMineshaftPieces.Type.SWAMPORDARKFOREST, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.spawnrate.swampAndDarkForestMineshaftSpawnrate, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.maxHeight.swampAndDarkForestMineshaftMaxHeight, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.minHeight.swampAndDarkForestMineshaftMinHeight);
    public static StructureFeature<DefaultFeatureConfig> TAIGA_MINESHAFT = new RSMineshaftStructure(RSMineshaftPieces.Type.TAIGA, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.spawnrate.taigaMineshaftSpawnrate, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.maxHeight.taigaMineshaftMaxHeight, RepurposedStructures.RSAllConfig.RSMineshaftsConfig.minHeight.taigaMineshaftMinHeight);

    public static StructureFeature<DefaultFeatureConfig> STONEBRICK_STRONGHOLD = new RSStonebrickStrongholdStructure();
    public static StructureFeature<DefaultFeatureConfig> NETHER_STRONGHOLD = new RSNetherStrongholdStructure();

    public static StructureFeature<DefaultFeatureConfig> JUNGLE_FORTRESS = new FortressJungleStructure();
    public static StructureFeature<DefaultFeatureConfig> GRASSY_IGLOO = new GenericJigsawStructure(new Identifier(RepurposedStructures.MODID, "igloos/grassy_top"), 20, 0, 0, 0, new HashSet<>());
    public static StructureFeature<DefaultFeatureConfig> STONE_IGLOO = new GenericJigsawStructure(new Identifier(RepurposedStructures.MODID, "igloos/stone_top"), 20, 0, 0, 0, new HashSet<>());

    public static StructureFeature<DefaultFeatureConfig> NETHER_WASTELAND_TEMPLE = new TempleNetherStructure(new Identifier(RepurposedStructures.MODID,"temples/temple_nether_wasteland"));
    public static StructureFeature<DefaultFeatureConfig> NETHER_BASALT_TEMPLE = new TempleNetherStructure(new Identifier(RepurposedStructures.MODID,"temples/temple_nether_basalt"));
    public static StructureFeature<DefaultFeatureConfig> NETHER_WARPED_TEMPLE = new TempleNetherStructure(new Identifier(RepurposedStructures.MODID,"temples/temple_nether_warped"));
    public static StructureFeature<DefaultFeatureConfig> NETHER_CRIMSON_TEMPLE = new TempleNetherStructure(new Identifier(RepurposedStructures.MODID,"temples/temple_nether_crimson"));
    public static StructureFeature<DefaultFeatureConfig> NETHER_SOUL_TEMPLE = new TempleNetherStructure(new Identifier(RepurposedStructures.MODID,"temples/temple_nether_soul"));

    public static StructureFeature<DefaultFeatureConfig> NETHER_BRICK_OUTPOST = new OutpostNetherStructure(new Identifier(RepurposedStructures.MODID,"outposts/nether_brick/base_plates"));
    public static StructureFeature<DefaultFeatureConfig> WARPED_OUTPOST = new OutpostNetherStructure(new Identifier(RepurposedStructures.MODID,"outposts/warped/base_plates"));
    public static StructureFeature<DefaultFeatureConfig> CRIMSON_OUTPOST = new OutpostNetherStructure(new Identifier(RepurposedStructures.MODID,"outposts/crimson/base_plates"));
    public static StructureFeature<DefaultFeatureConfig> OUTPOST_BIRCH = new GenericJigsawStructure(new Identifier(RepurposedStructures.MODID, "outposts/birch/base_plates"), 11, 0, 0, 5, Stream.of(RSStructureTagMap.STRUCTURE_TAGS.OVERWORLD_VILLAGE).collect(Collectors.toSet()), PillagerOutpostFeatureAccessor.rs_getMONSTER_SPAWNS(), ImmutableList.of());
    public static StructureFeature<DefaultFeatureConfig> OUTPOST_JUNGLE = new GenericJigsawStructure(new Identifier(RepurposedStructures.MODID, "outposts/jungle/base_plates"), 11, 0, 1, 5, Stream.of(RSStructureTagMap.STRUCTURE_TAGS.OVERWORLD_VILLAGE).collect(Collectors.toSet()), PillagerOutpostFeatureAccessor.rs_getMONSTER_SPAWNS(), ImmutableList.of());
    public static StructureFeature<DefaultFeatureConfig> OUTPOST_GIANT_TREE_TAIGA = new GenericJigsawStructure(new Identifier(RepurposedStructures.MODID, "outposts/giant_tree_taiga/base_plates"), 11, 0, 0, 5, Stream.of(RSStructureTagMap.STRUCTURE_TAGS.OVERWORLD_VILLAGE).collect(Collectors.toSet()), PillagerOutpostFeatureAccessor.rs_getMONSTER_SPAWNS(), ImmutableList.of());
    public static StructureFeature<DefaultFeatureConfig> OUTPOST_DESERT = new GenericJigsawStructure(new Identifier(RepurposedStructures.MODID, "outposts/desert/base_plates"), 11, 0, 1, 5, Stream.of(RSStructureTagMap.STRUCTURE_TAGS.OVERWORLD_VILLAGE).collect(Collectors.toSet()), PillagerOutpostFeatureAccessor.rs_getMONSTER_SPAWNS(), ImmutableList.of());
    public static StructureFeature<DefaultFeatureConfig> OUTPOST_BADLANDS = new GenericJigsawStructure(new Identifier(RepurposedStructures.MODID, "outposts/badlands/base_plates"), 11, 0, 0, 5, Stream.of(RSStructureTagMap.STRUCTURE_TAGS.OVERWORLD_VILLAGE).collect(Collectors.toSet()), 20, 1, PillagerOutpostFeatureAccessor.rs_getMONSTER_SPAWNS(), ImmutableList.of());
    public static StructureFeature<DefaultFeatureConfig> OUTPOST_SNOWY = new GenericJigsawStructure(new Identifier(RepurposedStructures.MODID, "outposts/snowy/base_plates"), 11, 0, 1, 5, Stream.of(RSStructureTagMap.STRUCTURE_TAGS.OVERWORLD_VILLAGE).collect(Collectors.toSet()), PillagerOutpostFeatureAccessor.rs_getMONSTER_SPAWNS(), ImmutableList.of());
    public static StructureFeature<DefaultFeatureConfig> OUTPOST_ICY = new GenericJigsawStructure(new Identifier(RepurposedStructures.MODID, "outposts/icy/base_plates"), 11, 0, 0, 5, Stream.of(RSStructureTagMap.STRUCTURE_TAGS.OVERWORLD_VILLAGE).collect(Collectors.toSet()), PillagerOutpostFeatureAccessor.rs_getMONSTER_SPAWNS(), ImmutableList.of());

    // Special thanks to /r/l-ll-ll-l_IsDisLoss for allowing me to mimic his nether pyramid design!
    public static StructureFeature<DefaultFeatureConfig> NETHER_PYRAMID = new GenericNetherJigsawHighStructure(new Identifier(RepurposedStructures.MODID, "temples/pyramid_nether"), 1, -4, 0);
    public static StructureFeature<DefaultFeatureConfig> BADLANDS_PYRAMID = new PyramidBadlandsStructure();

    public static StructureFeature<DefaultFeatureConfig> END_SHIPWRECK = new ShipwreckEndStructure();
    public static StructureFeature<DefaultFeatureConfig> NETHER_BRICKS_SHIPWRECK = new ShipwreckNetherStructure(new Identifier(RepurposedStructures.MODID, "shipwrecks/nether_bricks"), false);
    public static StructureFeature<DefaultFeatureConfig> CRIMSON_SHIPWRECK = new ShipwreckNetherStructure(new Identifier(RepurposedStructures.MODID, "shipwrecks/crimson"), true);
    public static StructureFeature<DefaultFeatureConfig> WARPED_SHIPWRECK = new ShipwreckNetherStructure(new Identifier(RepurposedStructures.MODID, "shipwrecks/warped"), true);

    public static StructureFeature<DefaultFeatureConfig> BADLANDS_VILLAGE = new GenericJigsawStructure(new Identifier(RepurposedStructures.MODID, "village/badlands/town_centers"), 10, 0, 1, 0, new HashSet<>(), 20, 2);
    public static StructureFeature<DefaultFeatureConfig> BIRCH_VILLAGE = new GenericJigsawStructure(new Identifier(RepurposedStructures.MODID, "village/birch/town_centers"), 6, 0, 1, 0, new HashSet<>());
    public static StructureFeature<DefaultFeatureConfig> DARK_FOREST_VILLAGE = new GenericJigsawStructure(new Identifier(RepurposedStructures.MODID, "village/dark_forest/town_centers"), 6, 0, 1, 0, new HashSet<>());
    public static StructureFeature<DefaultFeatureConfig> JUNGLE_VILLAGE = new GenericJigsawStructure(new Identifier(RepurposedStructures.MODID, "village/jungle/town_centers"), 8, 0, 1, 0, new HashSet<>());
    public static StructureFeature<DefaultFeatureConfig> SWAMP_VILLAGE = new GenericJigsawStructure(new Identifier(RepurposedStructures.MODID, "village/swamp/town_centers"), 6, -1, 1, 0, new HashSet<>());
    public static StructureFeature<DefaultFeatureConfig> MOUNTAINS_VILLAGE = new GenericJigsawStructure(new Identifier(RepurposedStructures.MODID, "village/mountains/town_centers"), 6, 0, 1, 0, new HashSet<>());
    public static StructureFeature<DefaultFeatureConfig> GIANT_TAIGA_VILLAGE = new GenericJigsawStructure(new Identifier(RepurposedStructures.MODID, "village/giant_taiga/town_centers"), 6, 0, 1, 0, new HashSet<>());
    public static StructureFeature<DefaultFeatureConfig> CRIMSON_VILLAGE = new VillageNetherStructure(new Identifier(RepurposedStructures.MODID, "village/crimson/town_centers"), 6, 0, 1, 0, new HashSet<>());
    public static StructureFeature<DefaultFeatureConfig> WARPED_VILLAGE = new VillageNetherStructure(new Identifier(RepurposedStructures.MODID, "village/warped/town_centers"), 6, 0, 1, 0, new HashSet<>());
    public static StructureFeature<DefaultFeatureConfig> VILLAGE_OAK = new GenericJigsawStructure(new Identifier(RepurposedStructures.MODID, "village/oak/town_centers"), 6, 0, 1, 0, new HashSet<>());

    public static StructureFeature<DefaultFeatureConfig> RUINED_PORTAL_END = new RuinedPortalEndStructure(new Identifier(RepurposedStructures.MODID, "ruined_portal/end"), 20, -6, 0, 0, new HashSet<>());

    public static StructureFeature<DefaultFeatureConfig> RUINS_NETHER = new GenericNetherJigsawHighStructure(new Identifier(RepurposedStructures.MODID, "ruins/nether/start_pool"), 1, -4, -1);

    public static void registerStructures() {

        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "mineshaft_birch"), BIRCH_MINESHAFT).step(GenerationStep.Feature.UNDERGROUND_STRUCTURES).defaultConfig(new StructureConfig(1, 0, 399117345)).superflatFeature(BIRCH_MINESHAFT.configure(FeatureConfig.DEFAULT)).register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "mineshaft_desert"), DESERT_MINESHAFT).step(GenerationStep.Feature.UNDERGROUND_STRUCTURES).defaultConfig(new StructureConfig(1, 0, 1990612785)).superflatFeature(DESERT_MINESHAFT.configure(FeatureConfig.DEFAULT)).register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "mineshaft_end"), END_MINESHAFT).step(GenerationStep.Feature.UNDERGROUND_STRUCTURES).defaultConfig(new StructureConfig(1, 0, 2057488602)).superflatFeature(END_MINESHAFT.configure(FeatureConfig.DEFAULT)).register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "mineshaft_nether"), NETHER_MINESHAFT).step(GenerationStep.Feature.UNDERGROUND_STRUCTURES).defaultConfig(new StructureConfig(1, 0, 1220811654)).superflatFeature(NETHER_MINESHAFT.configure(FeatureConfig.DEFAULT)).register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "mineshaft_icy"), ICY_MINESHAFT).step(GenerationStep.Feature.UNDERGROUND_STRUCTURES).defaultConfig(new StructureConfig(1, 0, 1451015246)).superflatFeature(ICY_MINESHAFT.configure(FeatureConfig.DEFAULT)).register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "mineshaft_jungle"), JUNGLE_MINESHAFT).step(GenerationStep.Feature.UNDERGROUND_STRUCTURES).defaultConfig(new StructureConfig(1, 0, 1434412876)).superflatFeature(JUNGLE_MINESHAFT.configure(FeatureConfig.DEFAULT)).register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "mineshaft_ocean"), OCEAN_MINESHAFT).step(GenerationStep.Feature.UNDERGROUND_STRUCTURES).defaultConfig(new StructureConfig(1, 0, 1774808662)).superflatFeature(OCEAN_MINESHAFT.configure(FeatureConfig.DEFAULT)).register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "mineshaft_savanna"), SAVANNA_MINESHAFT).step(GenerationStep.Feature.UNDERGROUND_STRUCTURES).defaultConfig(new StructureConfig(1, 0, 1960212212)).superflatFeature(SAVANNA_MINESHAFT.configure(FeatureConfig.DEFAULT)).register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "mineshaft_stone"), STONE_MINESHAFT).step(GenerationStep.Feature.UNDERGROUND_STRUCTURES).defaultConfig(new StructureConfig(1, 0, 1436736620)).superflatFeature(STONE_MINESHAFT.configure(FeatureConfig.DEFAULT)).register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "mineshaft_swamp_or_dark_forest"), SWAMP_OR_DARK_FOREST_MINESHAFT).step(GenerationStep.Feature.UNDERGROUND_STRUCTURES).defaultConfig(new StructureConfig(1, 0, 2037177700)).superflatFeature(SWAMP_OR_DARK_FOREST_MINESHAFT.configure(FeatureConfig.DEFAULT)).register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "mineshaft_taiga"), TAIGA_MINESHAFT).step(GenerationStep.Feature.UNDERGROUND_STRUCTURES).defaultConfig(new StructureConfig(1, 0, 1383003172)).superflatFeature(TAIGA_MINESHAFT.configure(FeatureConfig.DEFAULT)).register();

        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "stronghold_stonebrick"), STONEBRICK_STRONGHOLD).step(GenerationStep.Feature.UNDERGROUND_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSStrongholdsConfig.stonebrick.stonebrickStrongholdMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSStrongholdsConfig.stonebrick.stonebrickStrongholdMaxChunkDistance * 0.5f), 1098192663)).superflatFeature(STONEBRICK_STRONGHOLD.configure(FeatureConfig.DEFAULT)).register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "stronghold_nether"), NETHER_STRONGHOLD).step(GenerationStep.Feature.UNDERGROUND_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSStrongholdsConfig.nether.netherStrongholdMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSStrongholdsConfig.nether.netherStrongholdMaxChunkDistance * 0.5f), 1731422513)).superflatFeature(NETHER_STRONGHOLD.configure(FeatureConfig.DEFAULT)).register();

        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "fortress_jungle"), JUNGLE_FORTRESS).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSMainConfig.jungleFortress.jungleFortressMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSMainConfig.jungleFortress.jungleFortressMaxChunkDistance * 0.5f), 1464189157)).superflatFeature(JUNGLE_FORTRESS.configure(FeatureConfig.DEFAULT)).register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "igloo_grassy"), GRASSY_IGLOO).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSMainConfig.igloos.grassyIglooMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSMainConfig.igloos.grassyIglooMaxChunkDistance * 0.5f), 1460835582)).superflatFeature(GRASSY_IGLOO.configure(FeatureConfig.DEFAULT)).adjustsSurface().register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "igloo_stone"), STONE_IGLOO).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSMainConfig.igloos.stoneIglooMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSMainConfig.igloos.stoneIglooMaxChunkDistance * 0.5f), 1327429039)).superflatFeature(STONE_IGLOO.configure(FeatureConfig.DEFAULT)).adjustsSurface().register();

        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "temple_nether_wasteland"), NETHER_WASTELAND_TEMPLE).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSTemplesConfig.temples.netherWastelandTempleMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSTemplesConfig.temples.netherWastelandTempleMaxChunkDistance * 0.5f), 1435489909)).superflatFeature(NETHER_WASTELAND_TEMPLE.configure(FeatureConfig.DEFAULT)).register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "temple_nether_soul"), NETHER_SOUL_TEMPLE).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSTemplesConfig.temples.netherSoulTempleMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSTemplesConfig.temples.netherSoulTempleMaxChunkDistance * 0.5f), 1799485937)).superflatFeature(NETHER_SOUL_TEMPLE.configure(FeatureConfig.DEFAULT)).register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "temple_nether_basalt"), NETHER_BASALT_TEMPLE).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSTemplesConfig.temples.netherBasaltTempleMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSTemplesConfig.temples.netherBasaltTempleMaxChunkDistance * 0.5f), 1063117750)).superflatFeature(NETHER_BASALT_TEMPLE.configure(FeatureConfig.DEFAULT)).register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "temple_nether_crimson"), NETHER_CRIMSON_TEMPLE).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSTemplesConfig.temples.netherCrimsonTempleMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSTemplesConfig.temples.netherCrimsonTempleMaxChunkDistance * 0.5f), 1898896156)).superflatFeature(NETHER_CRIMSON_TEMPLE.configure(FeatureConfig.DEFAULT)).register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "temple_nether_warped"), NETHER_WARPED_TEMPLE).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSTemplesConfig.temples.netherWarpedTempleMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSTemplesConfig.temples.netherWarpedTempleMaxChunkDistance * 0.5f), 1635542708)).superflatFeature(NETHER_WARPED_TEMPLE.configure(FeatureConfig.DEFAULT)).register();

        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "outpost_nether_brick"), NETHER_BRICK_OUTPOST).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSOutpostsConfig.outposts.netherBrickOutpostMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSOutpostsConfig.outposts.netherBrickOutpostMaxChunkDistance * 0.5f), 1305971394)).superflatFeature(NETHER_BRICK_OUTPOST.configure(FeatureConfig.DEFAULT)).adjustsSurface().register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "outpost_warped"), WARPED_OUTPOST).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSOutpostsConfig.outposts.warpedOutpostMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSOutpostsConfig.outposts.warpedOutpostMaxChunkDistance * 0.5f), 1928816918)).superflatFeature(WARPED_OUTPOST.configure(FeatureConfig.DEFAULT)).adjustsSurface().register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "outpost_crimson"), CRIMSON_OUTPOST).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSOutpostsConfig.outposts.crimsonOutpostMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSOutpostsConfig.outposts.crimsonOutpostMaxChunkDistance * 0.5f), 1951425662)).superflatFeature(CRIMSON_OUTPOST.configure(FeatureConfig.DEFAULT)).adjustsSurface().register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "outpost_birch"), OUTPOST_BIRCH).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSOutpostsConfig.outposts.outpostBirchMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSOutpostsConfig.outposts.outpostBirchMaxChunkDistance * 0.5f), 1676743168)).superflatFeature(OUTPOST_BIRCH.configure(FeatureConfig.DEFAULT)).adjustsSurface().register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "outpost_jungle"), OUTPOST_JUNGLE).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSOutpostsConfig.outposts.outpostJungleMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSOutpostsConfig.outposts.outpostJungleMaxChunkDistance * 0.5f), 548433028)).superflatFeature(OUTPOST_JUNGLE.configure(FeatureConfig.DEFAULT)).adjustsSurface().register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "outpost_giant_tree_taiga"), OUTPOST_GIANT_TREE_TAIGA).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSOutpostsConfig.outposts.outpostGiantTreeTaigaMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSOutpostsConfig.outposts.outpostGiantTreeTaigaMaxChunkDistance * 0.5f), 993252541)).superflatFeature(OUTPOST_GIANT_TREE_TAIGA.configure(FeatureConfig.DEFAULT)).adjustsSurface().register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "outpost_desert"), OUTPOST_DESERT).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSOutpostsConfig.outposts.outpostDesertMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSOutpostsConfig.outposts.outpostDesertMaxChunkDistance * 0.5f), 593099376)).superflatFeature(OUTPOST_DESERT.configure(FeatureConfig.DEFAULT)).adjustsSurface().register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "outpost_badlands"), OUTPOST_BADLANDS).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSOutpostsConfig.outposts.outpostBadlandsMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSOutpostsConfig.outposts.outpostBadlandsMaxChunkDistance * 0.5f), 1702026868)).superflatFeature(OUTPOST_BADLANDS.configure(FeatureConfig.DEFAULT)).adjustsSurface().register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "outpost_snowy"), OUTPOST_SNOWY).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSOutpostsConfig.outposts.outpostSnowyMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSOutpostsConfig.outposts.outpostSnowyMaxChunkDistance * 0.5f), 849388460)).superflatFeature(OUTPOST_SNOWY.configure(FeatureConfig.DEFAULT)).adjustsSurface().register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "outpost_icy"), OUTPOST_ICY).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSOutpostsConfig.outposts.outpostIcyMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSOutpostsConfig.outposts.outpostIcyMaxChunkDistance * 0.5f), 935294633)).superflatFeature(OUTPOST_ICY.configure(FeatureConfig.DEFAULT)).adjustsSurface().register();

        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "pyramid_badlands"), BADLANDS_PYRAMID).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSTemplesConfig.pyramids.badlandsPyramidMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSTemplesConfig.pyramids.badlandsPyramidMaxChunkDistance * 0.5f), 1718729448)).superflatFeature(BADLANDS_PYRAMID.configure(FeatureConfig.DEFAULT)).register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "pyramid_nether"), NETHER_PYRAMID).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSTemplesConfig.pyramids.netherPyramidMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSTemplesConfig.pyramids.netherPyramidMaxChunkDistance * 0.5f), 2054372964)).superflatFeature(NETHER_PYRAMID.configure(FeatureConfig.DEFAULT)).adjustsSurface().register();

        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "shipwreck_end"), END_SHIPWRECK).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSShipwrecksConfig.maxChunkDistance.endShipwreckMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSShipwrecksConfig.maxChunkDistance.endShipwreckMaxChunkDistance * 0.5f), 1605500075)).superflatFeature(END_SHIPWRECK.configure(FeatureConfig.DEFAULT)).register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "shipwreck_nether_bricks"), NETHER_BRICKS_SHIPWRECK).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSShipwrecksConfig.maxChunkDistance.netherBricksShipwreckMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSShipwrecksConfig.maxChunkDistance.netherBricksShipwreckMaxChunkDistance * 0.5f), 2073308006)).superflatFeature(NETHER_BRICKS_SHIPWRECK.configure(FeatureConfig.DEFAULT)).register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "shipwreck_crimson"), CRIMSON_SHIPWRECK).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSShipwrecksConfig.maxChunkDistance.crimsonShipwreckMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSShipwrecksConfig.maxChunkDistance.crimsonShipwreckMaxChunkDistance * 0.5f), 1019716871)).superflatFeature(CRIMSON_SHIPWRECK.configure(FeatureConfig.DEFAULT)).adjustsSurface().register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "shipwreck_warped"), WARPED_SHIPWRECK).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSShipwrecksConfig.maxChunkDistance.warpedShipwreckMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSShipwrecksConfig.maxChunkDistance.warpedShipwreckMaxChunkDistance * 0.5f), 2072979641)).superflatFeature(WARPED_SHIPWRECK.configure(FeatureConfig.DEFAULT)).adjustsSurface().register();

        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "village_badlands"), BADLANDS_VILLAGE).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSVillagesConfig.badlandsVillageMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSVillagesConfig.badlandsVillageMaxChunkDistance * 0.5f), 1319707555)).superflatFeature(BADLANDS_VILLAGE.configure(FeatureConfig.DEFAULT)).adjustsSurface().register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "village_birch"), BIRCH_VILLAGE).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSVillagesConfig.birchVillageMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSVillagesConfig.birchVillageMaxChunkDistance * 0.5f), 1102567365)).superflatFeature(BIRCH_VILLAGE.configure(FeatureConfig.DEFAULT)).adjustsSurface().register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "village_dark_oak"), DARK_FOREST_VILLAGE).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSVillagesConfig.darkForestVillageMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSVillagesConfig.darkForestVillageMaxChunkDistance * 0.5f), 1921339358)).superflatFeature(DARK_FOREST_VILLAGE.configure(FeatureConfig.DEFAULT)).adjustsSurface().register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "village_jungle"), JUNGLE_VILLAGE).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSVillagesConfig.jungleVillageMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSVillagesConfig.jungleVillageMaxChunkDistance * 0.5f), 1229975218)).superflatFeature(JUNGLE_VILLAGE.configure(FeatureConfig.DEFAULT)).adjustsSurface().register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "village_swamp"), SWAMP_VILLAGE).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSVillagesConfig.swampVillageMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSVillagesConfig.swampVillageMaxChunkDistance * 0.5f), 1559650945)).superflatFeature(SWAMP_VILLAGE.configure(FeatureConfig.DEFAULT)).adjustsSurface().register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "village_mountains"), MOUNTAINS_VILLAGE).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSVillagesConfig.mountainsVillageMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSVillagesConfig.mountainsVillageMaxChunkDistance * 0.5f), 2010875989)).superflatFeature(MOUNTAINS_VILLAGE.configure(FeatureConfig.DEFAULT)).adjustsSurface().register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "village_giant_taiga"), GIANT_TAIGA_VILLAGE).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSVillagesConfig.giantTaigaVillageMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSVillagesConfig.giantTaigaVillageMaxChunkDistance * 0.5f), 1559528842)).superflatFeature(GIANT_TAIGA_VILLAGE.configure(FeatureConfig.DEFAULT)).adjustsSurface().register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "village_crimson"), CRIMSON_VILLAGE).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSVillagesConfig.crimsonVillageMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSVillagesConfig.crimsonVillageMaxChunkDistance * 0.5f), 1854750198)).superflatFeature(CRIMSON_VILLAGE.configure(FeatureConfig.DEFAULT)).adjustsSurface().register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "village_warped"), WARPED_VILLAGE).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSVillagesConfig.warpedVillageMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSVillagesConfig.warpedVillageMaxChunkDistance * 0.5f), 1298332136)).superflatFeature(WARPED_VILLAGE.configure(FeatureConfig.DEFAULT)).adjustsSurface().register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "village_oak"), VILLAGE_OAK).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSVillagesConfig.villageOakMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSVillagesConfig.villageOakMaxChunkDistance * 0.5f), 2112891039)).superflatFeature(VILLAGE_OAK.configure(FeatureConfig.DEFAULT)).adjustsSurface().register();

        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "ruined_portal_end"), RUINED_PORTAL_END).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSMainConfig.ruinedPortals.ruinedPortalEndMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSMainConfig.ruinedPortals.ruinedPortalEndMaxChunkDistance * 0.5f), 532404086)).superflatFeature(RUINED_PORTAL_END.configure(FeatureConfig.DEFAULT)).register();
        FabricStructureBuilder.create(new Identifier(RepurposedStructures.MODID, "ruins_nether"), RUINS_NETHER).step(GenerationStep.Feature.SURFACE_STRUCTURES).defaultConfig(new StructureConfig(RepurposedStructures.RSAllConfig.RSMainConfig.ruins.ruinsNetherMaxChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSMainConfig.ruins.ruinsNetherMaxChunkDistance * 0.5f), 1336047555)).superflatFeature(RUINS_NETHER.configure(FeatureConfig.DEFAULT)).adjustsSurface().register();

        //Next available seed: https://www.google.com/search?q=random+number

        RS_STRUCTURES.putAll(StructuresConfig.DEFAULT_STRUCTURES);
        RS_STRUCTURES.keySet().removeIf(key -> key.getName() == null || !key.getName().contains(RepurposedStructures.MODID));

        //registers the structure pieces.
        RSStructurePieces.registerStructurePieces();
    }
}
