package com.telepathicgrunt.repurposedstructures.modinit;

import com.google.common.collect.ImmutableSet;
import com.telepathicgrunt.repurposedstructures.RepurposedStructures;
import com.telepathicgrunt.repurposedstructures.world.structures.AdvancedDistanceJigsawStructure;
import com.telepathicgrunt.repurposedstructures.world.structures.AdvancedJigsawStructure;
import com.telepathicgrunt.repurposedstructures.world.structures.BuriableStructure;
import com.telepathicgrunt.repurposedstructures.world.structures.CityNetherStructure;
import com.telepathicgrunt.repurposedstructures.world.structures.GenericJigsawStructure;
import com.telepathicgrunt.repurposedstructures.world.structures.GenericNetherJigsawStructure;
import com.telepathicgrunt.repurposedstructures.world.structures.LandBasedEndStructure;
import com.telepathicgrunt.repurposedstructures.world.structures.MansionStructure;
import com.telepathicgrunt.repurposedstructures.world.structures.MineshaftEndStructure;
import com.telepathicgrunt.repurposedstructures.world.structures.MineshaftStructure;
import com.telepathicgrunt.repurposedstructures.world.structures.ShipwreckEndStructure;
import com.telepathicgrunt.repurposedstructures.world.structures.ShipwreckNetherStructure;
import com.telepathicgrunt.repurposedstructures.world.structures.StrongholdEndStructure;
import com.telepathicgrunt.repurposedstructures.world.structures.codeconfigs.AdvancedDistanceJigsawStructureCodeConfig;
import com.telepathicgrunt.repurposedstructures.world.structures.codeconfigs.AdvancedJigsawStructureCodeConfig;
import com.telepathicgrunt.repurposedstructures.world.structures.codeconfigs.BuriableStructureCodeConfig;
import com.telepathicgrunt.repurposedstructures.world.structures.codeconfigs.GenericJigsawStructureCodeConfig;
import com.telepathicgrunt.repurposedstructures.world.structures.codeconfigs.GenericNetherJigsawStructureCodeConfig;
import com.telepathicgrunt.repurposedstructures.world.structures.codeconfigs.MansionCodeConfig;
import com.telepathicgrunt.repurposedstructures.world.structures.codeconfigs.MineshaftCodeConfig;
import com.telepathicgrunt.repurposedstructures.world.structures.codeconfigs.ShipwreckNetherCodeConfig;
import com.telepathicgrunt.repurposedstructures.world.structures.codeconfigs.StartPoolOnlyCodeConfig;
import com.telepathicgrunt.repurposedstructures.world.structures.pieces.MansionPieces;
import net.fabricmc.fabric.api.structure.v1.FabricStructureBuilder;
import net.fabricmc.fabric.impl.structure.FabricStructureImpl;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.levelgen.GenerationStep;
import net.minecraft.world.level.levelgen.StructureSettings;
import net.minecraft.world.level.levelgen.feature.StructureFeature;
import net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration;
import net.minecraft.world.level.levelgen.feature.configurations.StructureFeatureConfiguration;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;


public final class RSStructures {
    private RSStructures() {}

    public static final Map<StructureFeature<?>, StructureFeatureConfiguration> RS_STRUCTURES = new HashMap<>();
    public static final Set<ResourceLocation> RS_STRUCTURE_START_PIECES = new HashSet<>();

    // MINESHAFTS

    public static StructureFeature<NoneFeatureConfiguration> MINESHAFT_BIRCH = MineshaftStructure.create(new MineshaftCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "mineshafts/birch/start_pool")).setStructureSize(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.size.birchMineshaftSize).setMaxY(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.maxHeight.birchMineshaftMaxHeight).setMinY(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.minHeight.birchMineshaftMinHeight).setProbability(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.spawnrate.birchMineshaftSpawnrate).build());
    public static StructureFeature<NoneFeatureConfiguration> MINESHAFT_DARK_FOREST = MineshaftStructure.create(new MineshaftCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "mineshafts/dark_forest/start_pool")).setStructureSize(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.size.darkForestMineshaftSize).setMaxY(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.maxHeight.darkForestMineshaftMaxHeight).setMinY(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.minHeight.darkForestMineshaftMinHeight).setProbability(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.spawnrate.darkForestMineshaftSpawnrate).build());
    public static StructureFeature<NoneFeatureConfiguration> MINESHAFT_DESERT = MineshaftStructure.create(new MineshaftCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "mineshafts/desert/start_pool")).setStructureSize(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.size.desertMineshaftSize).setMaxY(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.maxHeight.desertMineshaftMaxHeight).setMinY(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.minHeight.desertMineshaftMinHeight).setProbability(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.spawnrate.desertMineshaftSpawnrate).build());
    public static StructureFeature<NoneFeatureConfiguration> MINESHAFT_NETHER = MineshaftStructure.create(new MineshaftCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "mineshafts/nether/start_pool")).setStructureSize(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.size.netherMineshaftSize).setMaxY(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.maxHeight.netherMineshaftMaxHeight).setMinY(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.minHeight.netherMineshaftMinHeight).setProbability(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.spawnrate.netherMineshaftSpawnrate).build());
    public static StructureFeature<NoneFeatureConfiguration> MINESHAFT_CRIMSON = MineshaftStructure.create(new MineshaftCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "mineshafts/crimson/start_pool")).setStructureSize(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.size.crimsonMineshaftSize).setMaxY(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.maxHeight.crimsonMineshaftMaxHeight).setMinY(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.minHeight.crimsonMineshaftMinHeight).setProbability(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.spawnrate.crimsonMineshaftSpawnrate).build());
    public static StructureFeature<NoneFeatureConfiguration> MINESHAFT_WARPED = MineshaftStructure.create(new MineshaftCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "mineshafts/warped/start_pool")).setStructureSize(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.size.warpedMineshaftSize).setMaxY(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.maxHeight.warpedMineshaftMaxHeight).setMinY(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.minHeight.warpedMineshaftMinHeight).setProbability(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.spawnrate.warpedMineshaftSpawnrate).build());
    public static StructureFeature<NoneFeatureConfiguration> MINESHAFT_ICY = MineshaftStructure.create(new MineshaftCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "mineshafts/icy/start_pool")).setStructureSize(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.size.icyMineshaftSize).setMaxY(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.maxHeight.icyMineshaftMaxHeight).setMinY(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.minHeight.icyMineshaftMinHeight).setProbability(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.spawnrate.icyMineshaftSpawnrate).build());
    public static StructureFeature<NoneFeatureConfiguration> MINESHAFT_JUNGLE = MineshaftStructure.create(new MineshaftCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "mineshafts/jungle/start_pool")).setStructureSize(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.size.jungleMineshaftSize).setMaxY(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.maxHeight.jungleMineshaftMaxHeight).setMinY(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.minHeight.jungleMineshaftMinHeight).setProbability(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.spawnrate.jungleMineshaftSpawnrate).build());
    public static StructureFeature<NoneFeatureConfiguration> MINESHAFT_OCEAN = MineshaftStructure.create(new MineshaftCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "mineshafts/ocean/start_pool")).setStructureSize(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.size.oceanMineshaftSize).setMaxY(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.maxHeight.oceanMineshaftMaxHeight).setMinY(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.minHeight.oceanMineshaftMinHeight).setProbability(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.spawnrate.oceanMineshaftSpawnrate).build());
    public static StructureFeature<NoneFeatureConfiguration> MINESHAFT_SAVANNA = MineshaftStructure.create(new MineshaftCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "mineshafts/savanna/start_pool")).setStructureSize(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.size.savannaMineshaftSize).setMaxY(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.maxHeight.savannaMineshaftMaxHeight).setMinY(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.minHeight.savannaMineshaftMinHeight).setProbability(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.spawnrate.savannaMineshaftSpawnrate).build());
    public static StructureFeature<NoneFeatureConfiguration> MINESHAFT_STONE = MineshaftStructure.create(new MineshaftCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "mineshafts/stone/start_pool")).setStructureSize(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.size.stoneMineshaftSize).setMaxY(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.maxHeight.stoneMineshaftMaxHeight).setMinY(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.minHeight.stoneMineshaftMinHeight).setProbability(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.spawnrate.stoneMineshaftSpawnrate).build());
    public static StructureFeature<NoneFeatureConfiguration> MINESHAFT_SWAMP = MineshaftStructure.create(new MineshaftCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "mineshafts/swamp/start_pool")).setStructureSize(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.size.swampMineshaftSize).setMaxY(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.maxHeight.swampMineshaftMaxHeight).setMinY(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.minHeight.swampMineshaftMinHeight).setProbability(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.spawnrate.swampMineshaftSpawnrate).build());
    public static StructureFeature<NoneFeatureConfiguration> MINESHAFT_TAIGA = MineshaftStructure.create(new MineshaftCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "mineshafts/taiga/start_pool")).setStructureSize(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.size.taigaMineshaftSize).setMaxY(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.maxHeight.taigaMineshaftMaxHeight).setMinY(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.minHeight.taigaMineshaftMinHeight).setProbability(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.spawnrate.taigaMineshaftSpawnrate).build());
    public static StructureFeature<NoneFeatureConfiguration> MINESHAFT_END = MineshaftEndStructure.create(new MineshaftCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "mineshafts/end/start_pool")).setStructureSize(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.size.endMineshaftSize).setProbability(RepurposedStructures.RSAllConfig.RSMineshaftsConfig.spawnrate.endMineshaftSpawnrate).build());

    // STRONGHOLDS

    public static StructureFeature<NoneFeatureConfiguration> STRONGHOLD_NETHER = AdvancedDistanceJigsawStructure.create(new AdvancedDistanceJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "strongholds/nether/start_pool")).setStructureSize(RepurposedStructures.RSAllConfig.RSStrongholdsConfig.nether.netherStrongholdSize).setMaxY(RepurposedStructures.RSAllConfig.RSStrongholdsConfig.nether.netherStrongholdMaxHeight).setMinY(RepurposedStructures.RSAllConfig.RSStrongholdsConfig.nether.netherStrongholdMinHeight).setDistanceFromWorldOrigin(2817).build());
    public static StructureFeature<NoneFeatureConfiguration> STRONGHOLD_END = StrongholdEndStructure.create(new AdvancedDistanceJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "strongholds/end/start_pool")).setStructureSize(RepurposedStructures.RSAllConfig.RSStrongholdsConfig.end.endStrongholdSize).setMaxY(RepurposedStructures.RSAllConfig.RSStrongholdsConfig.end.endStrongholdMaxHeight).setMinY(RepurposedStructures.RSAllConfig.RSStrongholdsConfig.end.endStrongholdMinHeight).setVerticalRange(RepurposedStructures.RSAllConfig.RSStrongholdsConfig.end.endStrongholdVerticalRange).doNotClipOutOfBoundsPieces().setDistanceFromWorldOrigin(8000).build());

    // FORTRESSES

    public static StructureFeature<NoneFeatureConfiguration> FORTRESS_JUNGLE = AdvancedJigsawStructure.create(new AdvancedJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "fortresses/jungle/start_pool")).setStructureSize(RepurposedStructures.RSAllConfig.RSFortressesConfig.jungleFortress.jungleFortressSize).setBiomeRange(4).setMaxY(RepurposedStructures.RSAllConfig.RSFortressesConfig.jungleFortress.jungleFortressMaxHeight).setMinY(RepurposedStructures.RSAllConfig.RSFortressesConfig.jungleFortress.jungleFortressMinHeight).setVerticalRange(RepurposedStructures.RSAllConfig.RSFortressesConfig.jungleFortress.jungleFortressVerticalRange).doNotClipOutOfBoundsPieces().build());

    // IGLOOS

    public static StructureFeature<NoneFeatureConfiguration> IGLOO_GRASSY = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "igloos/grassy_top")).setStructureSize(20).cannotSpawnInWater().build());
    public static StructureFeature<NoneFeatureConfiguration> IGLOO_STONE = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "igloos/stone_top")).setStructureSize(20).cannotSpawnInWater().build());
    public static StructureFeature<NoneFeatureConfiguration> IGLOO_MUSHROOM = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "igloos/mushroom_top")).setStructureSize(20).cannotSpawnInWater().build());

    // TEMPLES

    public static StructureFeature<NoneFeatureConfiguration> TEMPLE_NETHER_WASTELAND = GenericNetherJigsawStructure.create(new GenericNetherJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "temples/nether_wasteland")).setStructureSize(8).canSpawnOnLiquid().build());
    public static StructureFeature<NoneFeatureConfiguration> TEMPLE_NETHER_BASALT = GenericNetherJigsawStructure.create(new GenericNetherJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "temples/nether_basalt")).setStructureSize(8).canSpawnOnLiquid().build());
    public static StructureFeature<NoneFeatureConfiguration> TEMPLE_NETHER_WARPED = GenericNetherJigsawStructure.create(new GenericNetherJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "temples/nether_warped")).setStructureSize(8).canSpawnOnLiquid().build());
    public static StructureFeature<NoneFeatureConfiguration> TEMPLE_NETHER_CRIMSON = GenericNetherJigsawStructure.create(new GenericNetherJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "temples/nether_crimson")).setStructureSize(8).canSpawnOnLiquid().build());
    public static StructureFeature<NoneFeatureConfiguration> TEMPLE_NETHER_SOUL = GenericNetherJigsawStructure.create(new GenericNetherJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "temples/nether_soul")).setStructureSize(8).canSpawnOnLiquid().build());

    // OUTPOSTS

    public static StructureFeature<NoneFeatureConfiguration> OUTPOST_NETHER_BRICK = GenericNetherJigsawStructure.create(new GenericNetherJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "outposts/nether_brick/base_plates")).setStructureSize(11).canSpawnOnLiquid().build());
    public static StructureFeature<NoneFeatureConfiguration> OUTPOST_WARPED = GenericNetherJigsawStructure.create(new GenericNetherJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "outposts/warped/base_plates")).setStructureSize(11).canSpawnOnLiquid().build());
    public static StructureFeature<NoneFeatureConfiguration> OUTPOST_CRIMSON = GenericNetherJigsawStructure.create(new GenericNetherJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "outposts/crimson/base_plates")).setStructureSize(11).canSpawnOnLiquid().build());
    public static StructureFeature<NoneFeatureConfiguration> OUTPOST_BIRCH = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "outposts/birch/base_plates")).setStructureSize(11).setStructureBlacklistRange(5).setAvoidStructuresSet(Stream.of(RSStructureTagMap.STRUCTURE_TAGS.OUTPOST_AVOID_STRUCTURE).collect(Collectors.toSet())).build());
    public static StructureFeature<NoneFeatureConfiguration> OUTPOST_JUNGLE = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "outposts/jungle/base_plates")).setStructureSize(11).setBiomeRange(1).setStructureBlacklistRange(5).setAvoidStructuresSet(Stream.of(RSStructureTagMap.STRUCTURE_TAGS.OUTPOST_AVOID_STRUCTURE).collect(Collectors.toSet())).build());
    public static StructureFeature<NoneFeatureConfiguration> OUTPOST_GIANT_TREE_TAIGA = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "outposts/giant_tree_taiga/base_plates")).setStructureSize(11).setStructureBlacklistRange(5).setAvoidStructuresSet(Stream.of(RSStructureTagMap.STRUCTURE_TAGS.OUTPOST_AVOID_STRUCTURE).collect(Collectors.toSet())).build());
    public static StructureFeature<NoneFeatureConfiguration> OUTPOST_DESERT = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "outposts/desert/base_plates")).setStructureSize(11).setBiomeRange(1).setStructureBlacklistRange(5).setAvoidStructuresSet(Stream.of(RSStructureTagMap.STRUCTURE_TAGS.OUTPOST_AVOID_STRUCTURE).collect(Collectors.toSet())).build());
    public static StructureFeature<NoneFeatureConfiguration> OUTPOST_BADLANDS = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "outposts/badlands/base_plates")).setStructureSize(11).setTerrainHeightRadius(1).setAllowTerrainHeightRange(20).setStructureBlacklistRange(5).setAvoidStructuresSet(Stream.of(RSStructureTagMap.STRUCTURE_TAGS.OUTPOST_AVOID_STRUCTURE).collect(Collectors.toSet())).build());
    public static StructureFeature<NoneFeatureConfiguration> OUTPOST_SNOWY = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "outposts/snowy/base_plates")).setStructureSize(11).setStructureBlacklistRange(5).setAvoidStructuresSet(Stream.of(RSStructureTagMap.STRUCTURE_TAGS.OUTPOST_AVOID_STRUCTURE).collect(Collectors.toSet())).build());
    public static StructureFeature<NoneFeatureConfiguration> OUTPOST_ICY = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "outposts/icy/base_plates")).setStructureSize(11).setBiomeRange(1).setStructureBlacklistRange(5).setAvoidStructuresSet(Stream.of(RSStructureTagMap.STRUCTURE_TAGS.OUTPOST_AVOID_STRUCTURE).collect(Collectors.toSet())).build());
    public static StructureFeature<NoneFeatureConfiguration> OUTPOST_TAIGA = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "outposts/taiga/base_plates")).setStructureSize(11).setBiomeRange(1).setStructureBlacklistRange(5).setAvoidStructuresSet(Stream.of(RSStructureTagMap.STRUCTURE_TAGS.OUTPOST_AVOID_STRUCTURE).collect(Collectors.toSet())).build());
    public static StructureFeature<NoneFeatureConfiguration> OUTPOST_OAK = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "outposts/oak/base_plates")).setStructureSize(11).setBiomeRange(1).setStructureBlacklistRange(5).setAvoidStructuresSet(Stream.of(RSStructureTagMap.STRUCTURE_TAGS.OUTPOST_AVOID_STRUCTURE).collect(Collectors.toSet())).build());
    public static StructureFeature<NoneFeatureConfiguration> OUTPOST_END = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "outposts/end/base_plates")).setStructureSize(11).setBiomeRange(2).setAllowTerrainHeightRange(3).setAllowTerrainHeightRange(15).setMinHeightLimit(55).setStructureBlacklistRange(4).setAvoidStructuresSet(Stream.of(RSStructureTagMap.STRUCTURE_TAGS.END_AVOID_STRUCTURE).collect(Collectors.toSet())).build());

    // PYRAMIDS

    public static StructureFeature<NoneFeatureConfiguration> PYRAMID_NETHER = GenericNetherJigsawStructure.create(new GenericNetherJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "pyramids/nether")).setStructureSize(8).searchForHighestLand().canSpawnOnLiquid().build());
    public static StructureFeature<NoneFeatureConfiguration> PYRAMID_BADLANDS = BuriableStructure.create(new BuriableStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "pyramids/badlands")).build());
    public static StructureFeature<NoneFeatureConfiguration> PYRAMID_DARK_FOREST = BuriableStructure.create(new BuriableStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "pyramids/dark_forest")).build());
    public static StructureFeature<NoneFeatureConfiguration> PYRAMID_SNOWY = BuriableStructure.create(new BuriableStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "pyramids/snowy")).build());
    public static StructureFeature<NoneFeatureConfiguration> PYRAMID_END = LandBasedEndStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "pyramids/end")).setStructureSize(11).setCenterOffset(-2).build());
    public static StructureFeature<NoneFeatureConfiguration> PYRAMID_ICY = BuriableStructure.create(new BuriableStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "pyramids/icy")).build());
    public static StructureFeature<NoneFeatureConfiguration> PYRAMID_JUNGLE = BuriableStructure.create(new BuriableStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "pyramids/jungle")).setOffsetAmount(20).build());
    public static StructureFeature<NoneFeatureConfiguration> PYRAMID_MUSHROOM = BuriableStructure.create(new BuriableStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "pyramids/mushroom")).build());
    public static StructureFeature<NoneFeatureConfiguration> PYRAMID_OCEAN = BuriableStructure.create(new BuriableStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "pyramids/ocean")).cannotSpawnInWater().useOceanHeightmap().build());
    public static StructureFeature<NoneFeatureConfiguration> PYRAMID_GIANT_TREE_TAIGA = BuriableStructure.create(new BuriableStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "pyramids/giant_tree_taiga")).build());
    public static StructureFeature<NoneFeatureConfiguration> PYRAMID_FLOWER_FOREST = BuriableStructure.create(new BuriableStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "pyramids/flower_forest")).build());

    // SHIPWRECKS

    public static StructureFeature<NoneFeatureConfiguration> SHIPWRECK_END = ShipwreckEndStructure.create(new StartPoolOnlyCodeConfig(new ResourceLocation(RepurposedStructures.MODID, "shipwrecks/end")));
    public static StructureFeature<NoneFeatureConfiguration> SHIPWRECK_NETHER_BRICKS = ShipwreckNetherStructure.create(new ShipwreckNetherCodeConfig(new ResourceLocation(RepurposedStructures.MODID, "shipwrecks/nether_bricks"), -3));
    public static StructureFeature<NoneFeatureConfiguration> SHIPWRECK_CRIMSON = ShipwreckNetherStructure.create(new ShipwreckNetherCodeConfig(new ResourceLocation(RepurposedStructures.MODID, "shipwrecks/crimson"), -4));
    public static StructureFeature<NoneFeatureConfiguration> SHIPWRECK_WARPED = ShipwreckNetherStructure.create(new ShipwreckNetherCodeConfig(new ResourceLocation(RepurposedStructures.MODID, "shipwrecks/warped"), -4));

    // VILLAGES

    public static StructureFeature<NoneFeatureConfiguration> VILLAGE_BADLANDS = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "villages/badlands/town_centers")).setStructureSize(RepurposedStructures.RSAllConfig.RSVillagesConfig.size.badlandsVillageSize).setBiomeRange(1).setTerrainHeightRadius(2).setAllowTerrainHeightRange(20).setStructureBlacklistRange(6).setAvoidStructuresSet(Stream.of(RSStructureTagMap.STRUCTURE_TAGS.MANSION, RSStructureTagMap.STRUCTURE_TAGS.VILLAGE_AVOID_STRUCTURE).collect(Collectors.toSet())).build());
    public static StructureFeature<NoneFeatureConfiguration> VILLAGE_BIRCH = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "villages/birch/town_centers")).setStructureSize(RepurposedStructures.RSAllConfig.RSVillagesConfig.size.birchVillageSize).setBiomeRange(1).setStructureBlacklistRange(6).setAvoidStructuresSet(Stream.of(RSStructureTagMap.STRUCTURE_TAGS.MANSION, RSStructureTagMap.STRUCTURE_TAGS.VILLAGE_AVOID_STRUCTURE).collect(Collectors.toSet())).build());
    public static StructureFeature<NoneFeatureConfiguration> VILLAGE_DARK_FOREST = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "villages/dark_forest/town_centers")).setStructureSize(RepurposedStructures.RSAllConfig.RSVillagesConfig.size.darkForestVillageSize).setBiomeRange(1).setStructureBlacklistRange(6).setAvoidStructuresSet(Stream.of(RSStructureTagMap.STRUCTURE_TAGS.MANSION, RSStructureTagMap.STRUCTURE_TAGS.VILLAGE_AVOID_STRUCTURE).collect(Collectors.toSet())).build());
    public static StructureFeature<NoneFeatureConfiguration> VILLAGE_JUNGLE = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "villages/jungle/town_centers")).setStructureSize(RepurposedStructures.RSAllConfig.RSVillagesConfig.size.jungleVillageSize).setBiomeRange(1).setStructureBlacklistRange(6).setAvoidStructuresSet(Stream.of(RSStructureTagMap.STRUCTURE_TAGS.MANSION, RSStructureTagMap.STRUCTURE_TAGS.VILLAGE_AVOID_STRUCTURE).collect(Collectors.toSet())).build());
    public static StructureFeature<NoneFeatureConfiguration> VILLAGE_SWAMP = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "villages/swamp/town_centers")).setStructureSize(RepurposedStructures.RSAllConfig.RSVillagesConfig.size.swampVillageSize).setCenterOffset(-1).setBiomeRange(1).setStructureBlacklistRange(6).setAvoidStructuresSet(Stream.of(RSStructureTagMap.STRUCTURE_TAGS.MANSION, RSStructureTagMap.STRUCTURE_TAGS.VILLAGE_AVOID_STRUCTURE).collect(Collectors.toSet())).build());
    public static StructureFeature<NoneFeatureConfiguration> VILLAGE_MOUNTAINS = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "villages/mountains/town_centers")).setStructureSize(RepurposedStructures.RSAllConfig.RSVillagesConfig.size.mountainsVillageSize).setBiomeRange(1).setStructureBlacklistRange(6).setAvoidStructuresSet(Stream.of(RSStructureTagMap.STRUCTURE_TAGS.MANSION, RSStructureTagMap.STRUCTURE_TAGS.VILLAGE_AVOID_STRUCTURE).collect(Collectors.toSet())).build());
    public static StructureFeature<NoneFeatureConfiguration> VILLAGE_GIANT_TAIGA = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "villages/giant_taiga/town_centers")).setStructureSize(RepurposedStructures.RSAllConfig.RSVillagesConfig.size.giantTaigaVillageSize).setBiomeRange(1).setStructureBlacklistRange(6).setAvoidStructuresSet(Stream.of(RSStructureTagMap.STRUCTURE_TAGS.MANSION, RSStructureTagMap.STRUCTURE_TAGS.VILLAGE_AVOID_STRUCTURE).collect(Collectors.toSet())).build());
    public static StructureFeature<NoneFeatureConfiguration> VILLAGE_OAK = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "villages/oak/town_centers")).setStructureSize(RepurposedStructures.RSAllConfig.RSVillagesConfig.size.oakVillageSize).setBiomeRange(1).setStructureBlacklistRange(6).setAvoidStructuresSet(Stream.of(RSStructureTagMap.STRUCTURE_TAGS.MANSION, RSStructureTagMap.STRUCTURE_TAGS.VILLAGE_AVOID_STRUCTURE).collect(Collectors.toSet())).build());
    public static StructureFeature<NoneFeatureConfiguration> VILLAGE_CRIMSON = GenericNetherJigsawStructure.create(new GenericNetherJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "villages/crimson/town_centers")).setStructureSize(RepurposedStructures.RSAllConfig.RSVillagesConfig.size.crimsonVillageSize).searchForHighestLand().setBiomeRange(1).setStructureBlacklistRange(10).setAvoidStructuresSet(Stream.of(RSStructureTagMap.STRUCTURE_TAGS.NETHER_OUTPOST).collect(Collectors.toSet())).build());
    public static StructureFeature<NoneFeatureConfiguration> VILLAGE_WARPED = GenericNetherJigsawStructure.create(new GenericNetherJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "villages/warped/town_centers")).setStructureSize(RepurposedStructures.RSAllConfig.RSVillagesConfig.size.warpedVillageSize).searchForHighestLand().setBiomeRange(1).setStructureBlacklistRange(10).setAvoidStructuresSet(Stream.of(RSStructureTagMap.STRUCTURE_TAGS.NETHER_OUTPOST).collect(Collectors.toSet())).build());
    public static StructureFeature<NoneFeatureConfiguration> VILLAGE_MUSHROOM = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "villages/mushroom/town_centers")).setStructureSize(RepurposedStructures.RSAllConfig.RSVillagesConfig.size.mushroomVillageSize).setBiomeRange(1).setStructureBlacklistRange(6).setAvoidStructuresSet(Stream.of(RSStructureTagMap.STRUCTURE_TAGS.MANSION, RSStructureTagMap.STRUCTURE_TAGS.VILLAGE_AVOID_STRUCTURE).collect(Collectors.toSet())).build());
    // regexpos1

    // RUINED PORTALS

    public static StructureFeature<NoneFeatureConfiguration> RUINED_PORTAL_END = LandBasedEndStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "ruined_portals/end")).setStructureSize(20).setCenterOffset(-6).build());

    // RUINS

    public static StructureFeature<NoneFeatureConfiguration> RUINS_NETHER = GenericNetherJigsawStructure.create(new GenericNetherJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "ruins/nether/start_pool")).setStructureSize(1).searchForHighestLand().canSpawnOnLiquid().setLedgeSpotOffset(-1).setLiquidSpotOffset(-2).build());
    public static StructureFeature<NoneFeatureConfiguration> RUINS_LAND_WARM = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "ruins/land_warm/start_pool")).setStructureSize(2).setTerrainHeightRadius(2).setAllowTerrainHeightRange(5).cannotSpawnInWater().build());
    public static StructureFeature<NoneFeatureConfiguration> RUINS_LAND_HOT = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "ruins/land_hot/start_pool")).setStructureSize(2).setTerrainHeightRadius(2).setAllowTerrainHeightRange(5).cannotSpawnInWater().build());
    public static StructureFeature<NoneFeatureConfiguration> RUINS_LAND_COLD = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "ruins/land_cold/start_pool")).setStructureSize(2).setTerrainHeightRadius(2).setAllowTerrainHeightRange(5).cannotSpawnInWater().build());
    public static StructureFeature<NoneFeatureConfiguration> RUINS_LAND_ICY = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "ruins/land_icy/start_pool")).setStructureSize(2).setTerrainHeightRadius(2).setAllowTerrainHeightRange(5).cannotSpawnInWater().build());

    // CITIES

    public static StructureFeature<NoneFeatureConfiguration> CITY_NETHER = CityNetherStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "cities/nether/start_pool")).setStructureSize(5).setStructureBlacklistRange(4).setAvoidStructuresSet(Stream.of(RSStructureTagMap.STRUCTURE_TAGS.GENERIC_AVOID_NETHER_STRUCTURE).collect(Collectors.toSet())).setPoolsThatIgnoreBounds(Set.of(new ResourceLocation(RepurposedStructures.MODID, "cities/nether/bridge_end"), new ResourceLocation(RepurposedStructures.MODID, "cities/nether/tower_top"), new ResourceLocation(RepurposedStructures.MODID, "cities/nether/fat_tower_top"))).build());
    public static StructureFeature<NoneFeatureConfiguration> CITY_OVERWORLD = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "cities/overworld/start_pool")).setStructureSize(5).setStructureBlacklistRange(4).setAvoidStructuresSet(Stream.of(RSStructureTagMap.STRUCTURE_TAGS.MANSION_AVOID_STRUCTURE).collect(Collectors.toSet())).setPoolsThatIgnoreBounds(Set.of(new ResourceLocation(RepurposedStructures.MODID, "cities/overworld/bridge_end"), new ResourceLocation(RepurposedStructures.MODID, "cities/overworld/tower_top"), new ResourceLocation(RepurposedStructures.MODID, "cities/overworld/fat_tower_top"))).cannotSpawnInWater().build());

    // MANSIONS

    public static StructureFeature<NoneFeatureConfiguration> MANSION_BIRCH = MansionStructure.create(new MansionCodeConfig(MansionPieces.MANSIONTYPE.BIRCH));
    public static StructureFeature<NoneFeatureConfiguration> MANSION_JUNGLE = MansionStructure.create(new MansionCodeConfig(MansionPieces.MANSIONTYPE.JUNGLE));
    public static StructureFeature<NoneFeatureConfiguration> MANSION_OAK = MansionStructure.create(new MansionCodeConfig(MansionPieces.MANSIONTYPE.OAK));
    public static StructureFeature<NoneFeatureConfiguration> MANSION_SAVANNA = MansionStructure.create(new MansionCodeConfig(MansionPieces.MANSIONTYPE.SAVANNA));
    public static StructureFeature<NoneFeatureConfiguration> MANSION_TAIGA = MansionStructure.create(new MansionCodeConfig(MansionPieces.MANSIONTYPE.TAIGA));
    public static StructureFeature<NoneFeatureConfiguration> MANSION_DESERT = MansionStructure.create(new MansionCodeConfig(MansionPieces.MANSIONTYPE.DESERT));
    public static StructureFeature<NoneFeatureConfiguration> MANSION_SNOWY = MansionStructure.create(new MansionCodeConfig(MansionPieces.MANSIONTYPE.SNOWY));

    // WITCH HUTS

    public static StructureFeature<NoneFeatureConfiguration> WITCH_HUTS_OAK = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "witch_huts/oak_start_pool")).setStructureSize(11).build());
    public static StructureFeature<NoneFeatureConfiguration> WITCH_HUTS_TAIGA = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "witch_huts/taiga_start_pool")).setStructureSize(11).build());
    public static StructureFeature<NoneFeatureConfiguration> WITCH_HUTS_BIRCH = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "witch_huts/birch_start_pool")).setStructureSize(11).build());
    public static StructureFeature<NoneFeatureConfiguration> WITCH_HUTS_DARK_FOREST = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "witch_huts/dark_forest_start_pool")).setStructureSize(11).build());
    public static StructureFeature<NoneFeatureConfiguration> WITCH_HUTS_GIANT_TREE_TAIGA = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "witch_huts/giant_tree_taiga_start_pool")).setStructureSize(11).build());

    // BASTIONS

    public static StructureFeature<NoneFeatureConfiguration> BASTION_UNDERGROUND = GenericJigsawStructure.create(new GenericJigsawStructureCodeConfig.Builder<>(new ResourceLocation(RepurposedStructures.MODID, "bastions/underground/starts")).setStructureSize(10).setFixedYSpawn(-45).doNotUseHeightmap().setBiomeRange(7).setStructureBlacklistRange(5).setAvoidStructuresSet(ImmutableSet.of(RSStructureTagMap.STRUCTURE_TAGS.BASTION_AVOID_STRUCTURE)).build());



    public static void registerStructures() {
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "mineshaft_birch"), MINESHAFT_BIRCH).step(GenerationStep.Decoration.UNDERGROUND_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(1, 0, 399117345)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "mineshaft_dark_forest"), MINESHAFT_DARK_FOREST).step(GenerationStep.Decoration.UNDERGROUND_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(1, 0, 2011511156)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "mineshaft_desert"), MINESHAFT_DESERT).step(GenerationStep.Decoration.UNDERGROUND_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(1, 0, 1990612785)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "mineshaft_nether"), MINESHAFT_NETHER).step(GenerationStep.Decoration.FLUID_SPRINGS).defaultConfig(new StructureFeatureConfiguration(1, 0, 1220811654)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "mineshaft_crimson"), MINESHAFT_CRIMSON).step(GenerationStep.Decoration.FLUID_SPRINGS).defaultConfig(new StructureFeatureConfiguration(1, 0, 1153019610)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "mineshaft_warped"), MINESHAFT_WARPED).step(GenerationStep.Decoration.FLUID_SPRINGS).defaultConfig(new StructureFeatureConfiguration(1, 0, 1095888662)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "mineshaft_icy"), MINESHAFT_ICY).step(GenerationStep.Decoration.UNDERGROUND_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(1, 0, 1451015246)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "mineshaft_jungle"), MINESHAFT_JUNGLE).step(GenerationStep.Decoration.UNDERGROUND_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(1, 0, 1434412876)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "mineshaft_ocean"), MINESHAFT_OCEAN).step(GenerationStep.Decoration.UNDERGROUND_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(1, 0, 1774808662)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "mineshaft_savanna"), MINESHAFT_SAVANNA).step(GenerationStep.Decoration.UNDERGROUND_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(1, 0, 1960212212)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "mineshaft_stone"), MINESHAFT_STONE).step(GenerationStep.Decoration.UNDERGROUND_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(1, 0, 1436736620)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "mineshaft_swamp"), MINESHAFT_SWAMP).step(GenerationStep.Decoration.UNDERGROUND_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(1, 0, 2037177700)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "mineshaft_taiga"), MINESHAFT_TAIGA).step(GenerationStep.Decoration.UNDERGROUND_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(1, 0, 1383003172)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "mineshaft_end"), MINESHAFT_END).step(GenerationStep.Decoration.UNDERGROUND_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(1, 0, 2057488602)).register();

        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "stronghold_nether"), STRONGHOLD_NETHER).step(GenerationStep.Decoration.TOP_LAYER_MODIFICATION).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSStrongholdsConfig.nether.netherStrongholdAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSStrongholdsConfig.nether.netherStrongholdAverageChunkDistance * 0.5f), 1731422513)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "stronghold_end"), STRONGHOLD_END).step(GenerationStep.Decoration.STRONGHOLDS).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSStrongholdsConfig.end.endStrongholdAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSStrongholdsConfig.end.endStrongholdAverageChunkDistance * 0.5f), 1922886435)).register();

        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "fortress_jungle"), FORTRESS_JUNGLE).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSFortressesConfig.jungleFortress.jungleFortressAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSFortressesConfig.jungleFortress.jungleFortressAverageChunkDistance * 0.5f), 1464189157)).register();

        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "igloo_grassy"), IGLOO_GRASSY).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSIgloosConfig.grassyIglooAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSIgloosConfig.grassyIglooAverageChunkDistance * 0.5f), 1460835582)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "igloo_stone"), IGLOO_STONE).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSIgloosConfig.stoneIglooAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSIgloosConfig.stoneIglooAverageChunkDistance * 0.5f), 1327429039)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "igloo_mushroom"), IGLOO_MUSHROOM).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSIgloosConfig.mushroomIglooAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSIgloosConfig.mushroomIglooAverageChunkDistance * 0.5f), 1242234354)).adjustsSurface().register();

        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "temple_nether_wasteland"), TEMPLE_NETHER_WASTELAND).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSTemplesConfig.netherWastelandTempleAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSTemplesConfig.netherWastelandTempleAverageChunkDistance * 0.5f), 1435489909)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "temple_nether_soul"), TEMPLE_NETHER_SOUL).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSTemplesConfig.netherSoulTempleAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSTemplesConfig.netherSoulTempleAverageChunkDistance * 0.5f), 1799485937)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "temple_nether_basalt"), TEMPLE_NETHER_BASALT).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSTemplesConfig.netherBasaltTempleAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSTemplesConfig.netherBasaltTempleAverageChunkDistance * 0.5f), 1063117750)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "temple_nether_crimson"), TEMPLE_NETHER_CRIMSON).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSTemplesConfig.netherCrimsonTempleAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSTemplesConfig.netherCrimsonTempleAverageChunkDistance * 0.5f), 1898896156)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "temple_nether_warped"), TEMPLE_NETHER_WARPED).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSTemplesConfig.netherWarpedTempleAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSTemplesConfig.netherWarpedTempleAverageChunkDistance * 0.5f), 1635542708)).register();

        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "outpost_nether_brick"), OUTPOST_NETHER_BRICK).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSOutpostsConfig.netherBrickOutpostAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSOutpostsConfig.netherBrickOutpostAverageChunkDistance * 0.5f), 1305971394)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "outpost_warped"), OUTPOST_WARPED).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSOutpostsConfig.warpedOutpostAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSOutpostsConfig.warpedOutpostAverageChunkDistance * 0.5f), 1928816918)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "outpost_crimson"), OUTPOST_CRIMSON).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSOutpostsConfig.crimsonOutpostAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSOutpostsConfig.crimsonOutpostAverageChunkDistance * 0.5f), 1951425662)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "outpost_birch"), OUTPOST_BIRCH).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSOutpostsConfig.outpostBirchAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSOutpostsConfig.outpostBirchAverageChunkDistance * 0.5f), 1676743168)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "outpost_jungle"), OUTPOST_JUNGLE).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSOutpostsConfig.outpostJungleAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSOutpostsConfig.outpostJungleAverageChunkDistance * 0.5f), 548433028)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "outpost_giant_tree_taiga"), OUTPOST_GIANT_TREE_TAIGA).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSOutpostsConfig.outpostGiantTreeTaigaAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSOutpostsConfig.outpostGiantTreeTaigaAverageChunkDistance * 0.5f), 993252541)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "outpost_desert"), OUTPOST_DESERT).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSOutpostsConfig.outpostDesertAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSOutpostsConfig.outpostDesertAverageChunkDistance * 0.5f), 593099376)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "outpost_badlands"), OUTPOST_BADLANDS).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSOutpostsConfig.outpostBadlandsAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSOutpostsConfig.outpostBadlandsAverageChunkDistance * 0.5f), 1702026868)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "outpost_snowy"), OUTPOST_SNOWY).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSOutpostsConfig.outpostSnowyAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSOutpostsConfig.outpostSnowyAverageChunkDistance * 0.5f), 849388460)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "outpost_icy"), OUTPOST_ICY).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSOutpostsConfig.outpostIcyAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSOutpostsConfig.outpostIcyAverageChunkDistance * 0.5f), 935294633)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "outpost_taiga"), OUTPOST_TAIGA).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSOutpostsConfig.outpostTaigaAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSOutpostsConfig.outpostTaigaAverageChunkDistance * 0.5f), 272805097)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "outpost_oak"), OUTPOST_OAK).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSOutpostsConfig.outpostOakAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSOutpostsConfig.outpostOakAverageChunkDistance * 0.5f), 698118385)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "outpost_end"), OUTPOST_END).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSOutpostsConfig.outpostEndAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSOutpostsConfig.outpostEndAverageChunkDistance * 0.5f), 831830630)).adjustsSurface().register();

        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "pyramid_badlands"), PYRAMID_BADLANDS).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSPyramidsConfig.pyramidBadlandsAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSPyramidsConfig.pyramidBadlandsAverageChunkDistance * 0.5f), 1718729448)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "pyramid_nether"), PYRAMID_NETHER).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSPyramidsConfig.pyramidNetherAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSPyramidsConfig.pyramidNetherAverageChunkDistance * 0.5f), 2054372964)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "pyramid_dark_forest"), PYRAMID_DARK_FOREST).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSPyramidsConfig.pyramidDarkForestAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSPyramidsConfig.pyramidDarkForestAverageChunkDistance * 0.5f), 1983978348)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "pyramid_snowy"), PYRAMID_SNOWY).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSPyramidsConfig.pyramidSnowyAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSPyramidsConfig.pyramidSnowyAverageChunkDistance * 0.5f), 1630533493)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "pyramid_end"), PYRAMID_END).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSPyramidsConfig.pyramidEndAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSPyramidsConfig.pyramidEndAverageChunkDistance * 0.5f), 1145023315)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "pyramid_icy"), PYRAMID_ICY).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSPyramidsConfig.pyramidIcyAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSPyramidsConfig.pyramidIcyAverageChunkDistance * 0.5f), 884076931)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "pyramid_jungle"), PYRAMID_JUNGLE).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSPyramidsConfig.pyramidJungleAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSPyramidsConfig.pyramidJungleAverageChunkDistance * 0.5f), 1483015905)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "pyramid_mushroom"), PYRAMID_MUSHROOM).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSPyramidsConfig.pyramidMushroomAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSPyramidsConfig.pyramidMushroomAverageChunkDistance * 0.5f), 1035759391)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "pyramid_ocean"), PYRAMID_OCEAN).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSPyramidsConfig.pyramidOceanAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSPyramidsConfig.pyramidOceanAverageChunkDistance * 0.5f), 777281414)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "pyramid_giant_tree_taiga"), PYRAMID_GIANT_TREE_TAIGA).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSPyramidsConfig.pyramidGiantTreeTaigaAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSPyramidsConfig.pyramidGiantTreeTaigaAverageChunkDistance * 0.5f), 1977974973)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "pyramid_flower_forest"), PYRAMID_FLOWER_FOREST).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSPyramidsConfig.pyramidFlowerForestAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSPyramidsConfig.pyramidFlowerForestAverageChunkDistance * 0.5f), 1984904323)).register();

        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "shipwreck_end"), SHIPWRECK_END).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSShipwrecksConfig.endShipwreckAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSShipwrecksConfig.endShipwreckAverageChunkDistance * 0.5f), 1605500075)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "shipwreck_nether_bricks"), SHIPWRECK_NETHER_BRICKS).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSShipwrecksConfig.netherBricksShipwreckAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSShipwrecksConfig.netherBricksShipwreckAverageChunkDistance * 0.5f), 2073308006)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "shipwreck_crimson"), SHIPWRECK_CRIMSON).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSShipwrecksConfig.crimsonShipwreckAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSShipwrecksConfig.crimsonShipwreckAverageChunkDistance * 0.5f), 1019716871)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "shipwreck_warped"), SHIPWRECK_WARPED).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSShipwrecksConfig.warpedShipwreckAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSShipwrecksConfig.warpedShipwreckAverageChunkDistance * 0.5f), 2072979641)).register();

        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "village_badlands"), VILLAGE_BADLANDS).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSVillagesConfig.spawnrate.badlandsVillageAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSVillagesConfig.spawnrate.badlandsVillageAverageChunkDistance * 0.5f), 1319707555)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "village_birch"), VILLAGE_BIRCH).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSVillagesConfig.spawnrate.birchVillageAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSVillagesConfig.spawnrate.birchVillageAverageChunkDistance * 0.5f), 1102567365)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "village_dark_oak"), VILLAGE_DARK_FOREST).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSVillagesConfig.spawnrate.darkForestVillageAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSVillagesConfig.spawnrate.darkForestVillageAverageChunkDistance * 0.5f), 1921339358)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "village_jungle"), VILLAGE_JUNGLE).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSVillagesConfig.spawnrate.jungleVillageAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSVillagesConfig.spawnrate.jungleVillageAverageChunkDistance * 0.5f), 1229975218)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "village_swamp"), VILLAGE_SWAMP).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSVillagesConfig.spawnrate.swampVillageAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSVillagesConfig.spawnrate.swampVillageAverageChunkDistance * 0.5f), 1559650945)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "village_mountains"), VILLAGE_MOUNTAINS).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSVillagesConfig.spawnrate.mountainsVillageAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSVillagesConfig.spawnrate.mountainsVillageAverageChunkDistance * 0.5f), 2010875989)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "village_giant_taiga"), VILLAGE_GIANT_TAIGA).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSVillagesConfig.spawnrate.giantTaigaVillageAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSVillagesConfig.spawnrate.giantTaigaVillageAverageChunkDistance * 0.5f), 1559528842)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "village_crimson"), VILLAGE_CRIMSON).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSVillagesConfig.spawnrate.crimsonVillageAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSVillagesConfig.spawnrate.crimsonVillageAverageChunkDistance * 0.5f), 1854750198)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "village_warped"), VILLAGE_WARPED).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSVillagesConfig.spawnrate.warpedVillageAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSVillagesConfig.spawnrate.warpedVillageAverageChunkDistance * 0.5f), 1298332136)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "village_oak"), VILLAGE_OAK).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSVillagesConfig.spawnrate.oakVillageAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSVillagesConfig.spawnrate.oakVillageAverageChunkDistance * 0.5f), 2112891039)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "village_mushroom"), VILLAGE_MUSHROOM).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSVillagesConfig.spawnrate.villageMushroomAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSVillagesConfig.spawnrate.villageMushroomAverageChunkDistance * 0.5f), 1150624897)).adjustsSurface().register();
        // regexpos2

        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "ruined_portal_end"), RUINED_PORTAL_END).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSRuinedPortalsConfig.ruinedPortalEndAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSRuinedPortalsConfig.ruinedPortalEndAverageChunkDistance * 0.5f), 532404086)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "ruins_nether"), RUINS_NETHER).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSRuinsConfig.ruinsNetherAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSRuinsConfig.ruinsNetherAverageChunkDistance * 0.5f), 1336047555)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "ruins_land_warm"), RUINS_LAND_WARM).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSRuinsConfig.ruinsLandWarmAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSRuinsConfig.ruinsLandWarmAverageChunkDistance * 0.25f), 18646107)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "ruins_land_hot"), RUINS_LAND_HOT).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSRuinsConfig.ruinsLandHotAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSRuinsConfig.ruinsLandHotAverageChunkDistance * 0.25f), 1243670027)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "ruins_land_cold"), RUINS_LAND_COLD).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSRuinsConfig.ruinsLandColdAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSRuinsConfig.ruinsLandColdAverageChunkDistance * 0.25f), 1065432023)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "ruins_land_icy"), RUINS_LAND_ICY).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSRuinsConfig.ruinsLandIcyAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSRuinsConfig.ruinsLandIcyAverageChunkDistance * 0.25f), 298896106)).adjustsSurface().register();

        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "city_nether"), CITY_NETHER).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSCitiesConfig.cityNetherAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSCitiesConfig.cityNetherAverageChunkDistance * 0.5f), 2082652405)).adjustsSurface().register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "city_overworld"), CITY_OVERWORLD).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSCitiesConfig.cityOverworldAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSCitiesConfig.cityOverworldAverageChunkDistance * 0.5f), 1225875111)).register();

        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "mansion_birch"), MANSION_BIRCH).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSMansionsConfig.mansionBirchAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSMansionsConfig.mansionBirchAverageChunkDistance * 0.5f), 182367035)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "mansion_jungle"), MANSION_JUNGLE).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSMansionsConfig.mansionJungleAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSMansionsConfig.mansionJungleAverageChunkDistance * 0.5f), 1267916621)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "mansion_oak"), MANSION_OAK).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSMansionsConfig.mansionOakAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSMansionsConfig.mansionOakAverageChunkDistance * 0.5f), 147853731)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "mansion_savanna"), MANSION_SAVANNA).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSMansionsConfig.mansionSavannaAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSMansionsConfig.mansionSavannaAverageChunkDistance * 0.5f), 2024558925)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "mansion_taiga"), MANSION_TAIGA).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSMansionsConfig.mansionTaigaAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSMansionsConfig.mansionTaigaAverageChunkDistance * 0.5f), 418506505)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "mansion_desert"), MANSION_DESERT).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSMansionsConfig.mansionDesertAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSMansionsConfig.mansionDesertAverageChunkDistance * 0.5f), 724317387)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "mansion_snowy"), MANSION_SNOWY).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSMansionsConfig.mansionSnowyAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSMansionsConfig.mansionSnowyAverageChunkDistance * 0.5f), 1115107889)).register();

        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "witch_hut_oak"), WITCH_HUTS_OAK).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSWitchHutsConfig.witchHutsOakAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSWitchHutsConfig.witchHutsOakAverageChunkDistance * 0.5f), 741641348)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "witch_hut_taiga"), WITCH_HUTS_TAIGA).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSWitchHutsConfig.witchHutsTaigaAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSWitchHutsConfig.witchHutsTaigaAverageChunkDistance * 0.5f), 1925189659)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "witch_hut_birch"), WITCH_HUTS_BIRCH).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSWitchHutsConfig.witchHutsBirchAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSWitchHutsConfig.witchHutsBirchAverageChunkDistance * 0.5f), 904634508)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "witch_hut_dark_forest"), WITCH_HUTS_DARK_FOREST).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSWitchHutsConfig.witchHutsDarkForestAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSWitchHutsConfig.witchHutsDarkForestAverageChunkDistance * 0.5f), 165100151)).register();
        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "witch_hut_giant_tree_taiga"), WITCH_HUTS_GIANT_TREE_TAIGA).step(GenerationStep.Decoration.SURFACE_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSWitchHutsConfig.witchHutsGiantTreeTaigaAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSWitchHutsConfig.witchHutsGiantTreeTaigaAverageChunkDistance * 0.5f), 200289401)).register();

        FabricStructureBuilder.create(new ResourceLocation(RepurposedStructures.MODID, "bastion_underground"), BASTION_UNDERGROUND).step(GenerationStep.Decoration.UNDERGROUND_STRUCTURES).defaultConfig(new StructureFeatureConfiguration(RepurposedStructures.RSAllConfig.RSBastionsConfig.bastionUndergroundAverageChunkDistance, (int) (RepurposedStructures.RSAllConfig.RSBastionsConfig.bastionUndergroundAverageChunkDistance * 0.5f), 1359301629)).register();

        StructureSettings.DEFAULTS.entrySet().stream()
                .filter(entry -> entry.getKey().getFeatureName() == null || !entry.getKey().getFeatureName().contains(RepurposedStructures.MODID))
                .forEach(entry -> RS_STRUCTURES.put(entry.getKey(), entry.getValue()));

        FabricStructureImpl.STRUCTURE_TO_CONFIG_MAP.entrySet().stream()
                .filter(entry -> entry.getKey().getFeatureName() == null || !entry.getKey().getFeatureName().contains(RepurposedStructures.MODID))
                .forEach(entry -> RS_STRUCTURES.put(entry.getKey(), entry.getValue()));

        //registers the structure pieces.
        RSStructurePieces.registerStructurePieces();
    }
}
