modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="${issues_url}"
sourcesUrl="${sources_url}"
license="${license}"

[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_display_name}"
    displayURL="${homepage_url}"
    authors="${mod_author}"
    credits="${mod_credits}"
    description='''${mod_description}'''
    logoFile="${logo_neoforge}"
    logoBlur=false

[[mixins]]
    config = "${mod_id}-neoforge.mixins.json"

[[mixins]]
    config = "${mod_id}-common.mixins.json"

[dependencies]
"${mod_id}" = [
    { modId = "neoforge", type = "required", versionRange = "*", ordering = "NONE", side = "BOTH" },
    { modId = "minecraft", type = "required", versionRange = "[${minecraft_version},)", ordering = "NONE", side = "BOTH" },
]