modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="${issues_url}"
sourcesUrl="${sources_url}"

[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_display_name}"
    displayURL="${homepage_url}"
    authors="TelepathicGrunt"
    credits="Special thanks to /r/l-ll-ll-l_IsDisLoss, miguelforge, and cannon_foddr for donating some structures to this mod!"
    description='''${mod_description}'''
    logoFile= "assets/repurposed_structures/repurposed_structures_logo_wide.png"
    logoBlur=false

[[mixins]]
    config = "repurposed_structures-neoforge.mixins.json"

[[mixins]]
    config = "repurposed_structures-common.mixins.json"

[dependencies]
"${mod_id}" = [
    { modId = "neoforge", type = "required", versionRange = "*", ordering = "NONE", side = "BOTH" },
    { modId = "minecraft", type = "required", versionRange = "[${minecraft_version},)", ordering = "NONE", side = "BOTH" },
]